### ISSUE TITLE
PhoneGap Build: iOS build fails, Android build successful

### ISSUE THREAD

**Issue by calitidexvii** [PDF417/pdf417-phonegap#51]
When building with [PhoneGap Build](https://build.phonegap.com/), the iOS build fails, while the Android build is successful. This is likely due to case-sensitivity in naming/references to MicroBlink.bundle and MicroBlink.framework.

See similar issue in [BlinkID repo](https://github.com/BlinkID/blinkid-phonegap/issues/60#issuecomment-383911942):

> Change and replace every instance of Microblink.bundle and Microblink.framework to MicroBlink.bundle and MicroBlink.framework.

**Comment by jcular** [comment]
Hi @calitidexvii,

did renaming help, we updated the script so this shouldn't be a problem anymore.

Kind regards,
Jure

**Comment by calitidexvii** [comment]
@jcular, as of yesterday, the build still failed with the [currently published npm version](https://www.npmjs.com/package/pdf417-cordova) (7.0.1-0). It looks like the npm package is out of date from the git repo. Could that be the problem?

Here's a [gist](https://gist.github.com/calitidexvii/48e7cb058a95b2dc025ee698daef0ce9) of the failed build for reference.

**Comment by jcular** [comment]
Hi @calitidexvii,

yes, you are right npm package wasn't updated
I'll update it asap.

Kind regards,
Jure

**Comment by calitidexvii** [comment]
Thanks for updating the npm package, @jcular. However, I'm still seeing the error during build.

Here's an [updated gist](https://gist.github.com/calitidexvii/a120322026d8e0474e97ae00b62aafed) of the error log, run using the updated npm package. I've tried the build again with the latest and oldest [PhoneGap Build versions](https://build.phonegap.com/current-support).

I have the package version locked in the config.xml file as such:

`<plugin name="pdf417-cordova" source="npm" spec="~7.0.1" />`

**Comment by calitidexvii** [comment]
Hi @jcular,

We've decided to build the project directly instead of using PhoneGap Build. The build is successful and deploys to test devices.

Feel free to close this issue unless you want to continue troubleshooting.

**Comment by jcular** [comment]
Hi @calitidexvii,

I'll keep this open until we resolve the issue, 
thank you for reporting this issue.

Kind regards,
Jure

**Comment by jcular** [comment]
Hi @calitidexvii,

can you tell me if you had **wget** and **unzip** installed?

Kind regards,
Jure

**Comment by calitidexvii** [comment]
Hi @jcular, This was on the [PhoneGap Build](https://build.phonegap.com/) service, so I couldn't see the system setup (that's why we setup our own build machine.) That could have been the problem.
